#!/bin/sh
arch=$(uname -m)

# Set build argument if ARM
if [[ "$arch" == "arm64" || "$arch" == "aarch64" ]]; then
  docker build -t chrome-cxx-libreoffice:0.0.1 --build-arg ARCH=-arm64 .
else
  docker build -t chrome-cxx-libreoffice:0.0.1 .
fi
mkdir -p .cache .npm .config .gsutil
exec docker run \
  --rm \
  -it \
  -v $(pwd):/app:rw \
  -v $(pwd)/.cache:/.cache:rw \
  -v $(pwd)/.npm:/.npm:rw \
  -v $(pwd)/.config:/.config:rw \
  -v $(pwd)/.gsutil:/.gsutil:rw \
  -u $(id -u):$(id -g) \
  -w /app \
  chrome-cxx-libreoffice:0.0.1 \
  bash
